export const Courses = [
  {
    id: 1,
    imagePreview: "/img/image-preview-course.png",
    level: "All levels",
    skill: "Speaking Skills",
    nameCourse: "Master Your Pronunciation Course",
    priceCourse: 20,
  },
  {
    id: 2,
    imagePreview: "/img/image-preview-course.png",
    level: "Basic level",
    skill: "Speaking Skills",
    nameCourse: "Master Your Pronunciation Course",
    priceCourse: 20,
  },
  {
    id: 3,
    imagePreview: "/img/image-preview-course.png",
    level: "Advanced level",
    skill: "Speaking Skills",
    nameCourse: "Master Your Pronunciation Course",
    priceCourse: 20,
  },
  {
    id: 4,
    imagePreview: "/img/image-preview-course.png",
    level: "All levels",
    skill: "Speaking Skills",
    nameCourse: "Master Your Pronunciation Course",
    priceCourse: 20,
  },
  {
    id: 5,
    imagePreview: "/img/image-preview-course.png",
    level: "All levels",
    skill: "Speaking Skills",
    nameCourse: "Master Your Pronunciation Course",
    priceCourse: 20,
  },
];
